### ISSUE TITLE
Bot Sharder - needs an update for V12

### ISSUE THREAD

**Issue by master3395** [Discord-Bot-Maker-Mods/DBM-Custom-BotJS-Files#4]
client.shard && client.shard.fetchClientValues('users.size')
needs to use cache
client.shard && client.shard.fetchClientValues('users.cache.size')

So does
client.shard && client.shard.fetchClientValues('guilds.size')
client.shard && client.shard.fetchClientValues('guilds.cache.size')

Also, shard and ID shows up as NaN and undefined.

![image](https://user-images.githubusercontent.com/4199669/91670163-42779900-eb1b-11ea-8777-b6dd211f4fce.png)

https://github.com/dbm-network/custom-files/tree/dbm-1.3.0%2B/Bot%20Sharder

**Comment by Mikaru0Mystic** [comment]
I agree, this could be useful as hell, i have found a lot of problems with sharding. Have tried some stuff myself but didnt go well. The last time the custom files were updates was 2/3 years ago.
